export const ADD_ARTICLE = "ADD_ARTICLE";
export const OPEN_MODEL = "OPEN_MODEL";
export const SELECT_TOKEN = "SELECT_TOKEN";
export const RECEIVE_TOKEN = 'RECEIVE_TOKEN';
export const CONNECT_WALLET = 'CONNECT_WALLET';
export const CONNET_NETWORK = 'CONNET_NETWORK'