export const data = [
  {
    icon: '/images/coin6.png',
    name: '1inch',
    get: 'You Can Get USDT',
    proce: '556.60',
    pr: '(+0.06%)',
    shortname: 'Price (ETH/USDT)',
    shortPrice: '106.82',
    gasfee: 'Gas Fee',
    gesprice: '$12.15',
  },
  {
    icon: '/images/ListIcon2.png',
    name: 'Matcha',
    get: 'You Can Get USDT',
    proce: '556.60',
    pr: '(+0.06%)',
    shortname: 'Price (ETH/USDT)',
    shortPrice: '106.82',
    gasfee: 'Gas Fee',
    gesprice: '$12.15',
  },
  {
    icon: '/images/ListIcon3.png',
    name: '1inch',
    get: 'You Can Get USDT',
    proce: '556.60',
    pr: '(+0.06%)',
    shortname: 'Price (ETH/USDT)',
    shortPrice: '106.82',
    gasfee: 'Gas Fee',
    gesprice: '$12.15',
  },
  {
    icon: '/images/ListIcon4.png',
    name: '1inch',
    get: 'You Can Get USDT',
    proce: '556.60',
    pr: '(+0.06%)',
    shortname: 'Price (ETH/USDT)',
    shortPrice: '106.82',
    gasfee: 'Gas Fee',
    gesprice: '$12.15',
  },
];
