export const list = [
  {
    name: 'Ethereum',
    icon: '/images/coin.png',
    status: true,
    count: 0,
    type: 'ETH',
  },
  {
    name: 'Avalanche',
    icon: '/images/coin2.png',
    status: false,
    count: 0,
    type: 'AVAX',
  },
  {
    name: 'Tether',
    icon: '/images/coin3.png',
    status: false,
    count: 0,
    type: 'USDT',
  },
  {
    name: 'Polygon',
    icon: '/images/coin4.png',
    status: false,
    count: 0,
    type: 'MATIC',
  },
  {
    name: 'Fantom',
    icon: '/images/coin5.png',
    status: false,
    count: 0,
    type: 'FTM',
  },
  {
    name: '1Inch',
    icon: '/images/coin6.png',
    status: false,
    count: 0,
    type: '1INCH',
  },
  {
    name: 'Chainlink',
    icon: '/images/coin7.png',
    status: false,
    count: 0,
    type: 'LINK',
  },
];
